export const NAMES_POOL = [
    'ALEX', 'RILEY', 'JORDAN', 'TAYLOR', 'CASEY', 'SKYLER', 'AVERY', 'MORGAN', 'CAMERON', 'JAMIE',
    'CHARLIE', 'ROWAN', 'QUINN', 'DAKOTA', 'EMERSON', 'PHOENIX', 'SAGE', 'BLAKE', 'LOGAN', 'FINLEY',
    'DREW', 'REAGAN', 'HAYDEN', 'PAISLEY', 'RIVER', 'AUBREY', 'HARPER', 'FRANKIE', 'ELLIS', 'PARKER',
    'REESE', 'ANDY', 'TERRY', 'MARLEY', 'LONDON', 'KAI', 'OAKLEY', 'AUSTIN', 'BILLIE', 'ALEXIS',
    'RYAN', 'SAM', 'MICHAEL', 'JO', 'CODY', 'ANGEL', 'ISRAEL', 'JESSE', 'BOBBIE', 'ARIEL',
    'TORY', 'JAYDEN', 'JULIAN', 'BLAIR', 'COREY', 'JULES', 'HARLEY', 'ZION', 'DEVON', 'NICO',
    'ASH', 'GREY', 'LENNON', 'TAYLOR', 'CASEY', 'SASHA', 'KENDALL', 'KIM', 'JORDYN', 'TORI',
    'RAY', 'SHILOH', 'LUX', 'NOEL', 'MICHELLE', 'ADRIAN', 'LEE', 'HOLLIS', 'KELLY', 'ARLO',
    'CARMEN', 'CORY', 'BRIAR', 'MILAN', 'LONDON', 'RAYNE', 'AKIRA', 'INDIGO', 'JAY', 'REMINGTON',
    'SHAY', 'OCEAN', 'ANGEL', 'DENVER', 'JODY', 'RYDER', 'LANE', 'MICAH', 'TAYLAN', 'LEX',
    'CHANDLER', 'DALLAS', 'BAY', 'BILLIE', 'HUNTER', 'JORDAN', 'AALI', 'MORGAN', 'BEAU', 'ASPEN',
    'KAIRO', 'JAZZ', 'ZURI', 'SALEM', 'KAI', 'TOVA', 'PEYTON', 'RAYAN', 'NOVA', 'ONI',
    'WREN', 'SKYE', 'OAK', 'KADEN', 'PAX', 'LINDSEY', 'HOLLAND', 'LUCA', 'SOREN', 'YARDEN',
    'AZARIAH', 'ELIOT', 'HARPER', 'COVE', 'SHAYNE', 'ROWAN', 'DARA', 'MORGAN', 'RAFI', 'KORI',
    'ZAYNE', 'GREER', 'KAI', 'ZEN', 'SAJ', 'ARIS', 'ZION', 'CYAN', 'RAE', 'EMERY',
    'SAGE', 'RAYE', 'ALEK', 'SOL', 'TALI', 'INDRA', 'SETH', 'REN', 'VANYA', 'SAMMI',
    'LIOR', 'WYNNE', 'JAMIE', 'TAMIR', 'BLAZE', 'STEVIE', 'ADLEY', 'MICKEY', 'SHANE', 'OCEANE',
    'CLOUD', 'MIKA', 'AVERY', 'JULES', 'LOU', 'SKY', 'ALEXI', 'NIKI', 'AMARI', 'KAYA',
    'ELI', 'BRI', 'JAE', 'LONDON', 'TALI', 'LEITH', 'NOA', 'MALIK', 'REMI', 'LEE',
    'NYX', 'TORREN', 'LENNON', 'ARTIE', 'RORY', 'ARYA', 'ISSA', 'PRESLEY', 'ELIS', 'MAKAI',
    'SHILOH', 'KIMANI', 'YURI', 'CALI', 'CAMILLE', 'RAE', 'MONROE', 'JONI', 'ZIA', 'ALEI'
];
  
