name: release

env:
  HUSKY: 0

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm run test -- --ci --maxWorkers=2
      #   env:
      #     NODE_OPTIONS: "--max-old-space-size=4096" # Increase heap size for jest

      - name: Create Release Pull Request or Publish Packages
        uses: changesets/action@v1
        with:
          version: npm run changeset:version
          publish: npm run changeset:publish
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}